# Site settings
title: "#BlockBlum"
email: info@18millionrising.org
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # 
url: "http://blockblum.18mr.org" # the base hostname & protocol for your site
twitter_username: 18millionrising
github_username: 18mr
github_projectname: blockblum
facebook_url:  'http://facebook.com/18MillionRising.org'

# Build settings
markdown: kramdown
permalink: title